package server

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"
	"unicode/utf8"

	"golang.org/x/crypto/bcrypt"
)

// sessionCookieName is the cookie carrying the opaque session token.
const sessionCookieName = "triagearr_session"

// generatedPasswordLength is the number of base64url chars the server hands
// back to the operator when they ask for an auto-generated password.
const generatedPasswordLength = 32

// minPasswordRunes is the minimum length for an operator-chosen password.
// Short by browser-form standards on purpose: the dashboard is single-user
// and the cookie/X-API-Key flow is rate-limited.
const minPasswordRunes = 12

type sessionStatusResponse struct {
	AuthEnabled   bool   `json:"auth_enabled"`
	Authenticated bool   `json:"authenticated"`
	Username      string `json:"username,omitempty"`
}

func (s *Server) handleSessionStatus(w http.ResponseWriter, r *http.Request) {
	resp := sessionStatusResponse{}
	enabled, err := s.authEnabled(r.Context())
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	resp.AuthEnabled = enabled
	if enabled {
		if uid, ok := s.resolveSession(r); ok {
			if u, err := s.opts.Store.GetAuthUserByID(r.Context(), uid); err == nil {
				resp.Authenticated = true
				resp.Username = u.Username
			}
		}
	}
	writeJSON(w, http.StatusOK, resp)
}

type sessionLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (s *Server) handleSessionLogin(w http.ResponseWriter, r *http.Request) {
	var req sessionLoginRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	enabled, err := s.authEnabled(r.Context())
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	if !enabled {
		writeError(w, http.StatusBadRequest, "authentication is not enabled")
		return
	}
	user, err := s.opts.Store.GetAuthUserByName(r.Context(), strings.TrimSpace(req.Username))
	if err != nil {
		// Constant-ish time: do a fake compare so timing doesn't leak presence.
		_ = bcrypt.CompareHashAndPassword([]byte("$2a$10$invalidinvalidinvalidinvalidinvalidinvalidinvalidinvalidinvalid"), []byte(req.Password))
		writeError(w, http.StatusUnauthorized, "invalid credentials")
		return
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Password)); err != nil {
		writeError(w, http.StatusUnauthorized, "invalid credentials")
		return
	}
	if err := s.issueSession(w, r, user.ID); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, sessionStatusResponse{
		AuthEnabled: true, Authenticated: true, Username: user.Username,
	})
}

func (s *Server) handleSessionLogout(w http.ResponseWriter, r *http.Request) {
	if c, err := r.Cookie(sessionCookieName); err == nil && c.Value != "" {
		_ = s.opts.Store.DeleteAuthSession(r.Context(), hashToken(c.Value))
	}
	clearSessionCookie(w, r)
	writeJSON(w, http.StatusOK, map[string]string{"status": "logged_out"})
}

type authEnableRequest struct {
	Username string `json:"username"`
	Password string `json:"password,omitempty"` // optional; auto-generated when empty
}

type authEnableResponse struct {
	Username string `json:"username"`
	Password string `json:"password,omitempty"` // present only when auto-generated
}

func (s *Server) handleAuthEnable(w http.ResponseWriter, r *http.Request) {
	enabled, err := s.authEnabled(r.Context())
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	if enabled {
		writeError(w, http.StatusConflict, "authentication is already enabled — use POST /api/v1/auth/password to rotate the password")
		return
	}
	var req authEnableRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	username := strings.TrimSpace(req.Username)
	if !validUsername(username) {
		writeError(w, http.StatusBadRequest, "username must be 3..32 chars, letters/digits/._-")
		return
	}
	password := req.Password
	autoGenerated := false
	if password == "" {
		password, err = generatePassword(generatedPasswordLength)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "generating password: "+err.Error())
			return
		}
		autoGenerated = true
	}
	if !validPassword(password) {
		writeError(w, http.StatusBadRequest, "password must be at least 12 characters")
		return
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "hashing password: "+err.Error())
		return
	}
	uid, err := s.opts.Store.InsertAuthUser(r.Context(), username, string(hash))
	if err != nil {
		writeError(w, http.StatusInternalServerError, "creating user: "+err.Error())
		return
	}
	if err := s.issueSession(w, r, uid); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	resp := authEnableResponse{Username: username}
	if autoGenerated {
		resp.Password = password // shown to the operator exactly once
	}
	writeJSON(w, http.StatusOK, resp)
}

type authDisableRequest struct {
	Password string `json:"password"`
}

func (s *Server) handleAuthDisable(w http.ResponseWriter, r *http.Request) {
	var req authDisableRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	uid, ok := userIDFromContext(r.Context())
	if !ok {
		// X-API-Key path: still require the current password to confirm.
		writeError(w, http.StatusForbidden, "disable must be performed from an authenticated UI session")
		return
	}
	user, err := s.opts.Store.GetAuthUserByID(r.Context(), uid)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Password)); err != nil {
		writeError(w, http.StatusUnauthorized, "invalid password")
		return
	}
	if err := s.opts.Store.DeleteAuthUser(r.Context(), uid); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	clearSessionCookie(w, r)
	writeJSON(w, http.StatusOK, map[string]string{"status": "disabled"})
}

type authChangePasswordRequest struct {
	Current string `json:"current"`
	New     string `json:"new,omitempty"`
}

type authChangePasswordResponse struct {
	Password string `json:"password,omitempty"` // present only when auto-generated
}

func (s *Server) handleAuthChangePassword(w http.ResponseWriter, r *http.Request) {
	var req authChangePasswordRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	uid, ok := userIDFromContext(r.Context())
	if !ok {
		writeError(w, http.StatusForbidden, "password change must be performed from an authenticated UI session")
		return
	}
	user, err := s.opts.Store.GetAuthUserByID(r.Context(), uid)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Current)); err != nil {
		writeError(w, http.StatusUnauthorized, "invalid current password")
		return
	}
	newPwd := req.New
	autoGenerated := false
	if newPwd == "" {
		newPwd, err = generatePassword(generatedPasswordLength)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "generating password: "+err.Error())
			return
		}
		autoGenerated = true
	}
	if !validPassword(newPwd) {
		writeError(w, http.StatusBadRequest, "password must be at least 12 characters")
		return
	}
	if subtle.ConstantTimeCompare([]byte(req.Current), []byte(newPwd)) == 1 {
		writeError(w, http.StatusBadRequest, "new password must differ from the current one")
		return
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(newPwd), bcrypt.DefaultCost)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "hashing password: "+err.Error())
		return
	}
	if err := s.opts.Store.UpdateAuthPassword(r.Context(), uid, string(hash)); err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	resp := authChangePasswordResponse{}
	if autoGenerated {
		resp.Password = newPwd
	}
	writeJSON(w, http.StatusOK, resp)
}

// issueSession mints a fresh opaque token, persists its hash, and sets the
// session cookie on the response.
func (s *Server) issueSession(w http.ResponseWriter, r *http.Request, userID int64) error {
	token, err := generateOpaqueToken(32)
	if err != nil {
		return errors.New("generating session token: " + err.Error())
	}
	expires := time.Now().UTC().Add(sessionTTL)
	if err := s.opts.Store.InsertAuthSession(r.Context(), hashToken(token), userID, expires); err != nil {
		return err
	}
	http.SetCookie(w, &http.Cookie{ //nolint:gosec // HttpOnly/SameSite set below; Secure tracks request scheme.
		Name:     sessionCookieName,
		Value:    token,
		Path:     "/",
		HttpOnly: true,
		Secure:   isRequestSecure(r),
		SameSite: http.SameSiteLaxMode,
		Expires:  expires,
	})
	return nil
}

func clearSessionCookie(w http.ResponseWriter, r *http.Request) {
	http.SetCookie(w, &http.Cookie{ //nolint:gosec // HttpOnly/SameSite set below; Secure tracks request scheme.
		Name:     sessionCookieName,
		Value:    "",
		Path:     "/",
		HttpOnly: true,
		Secure:   isRequestSecure(r),
		SameSite: http.SameSiteLaxMode,
		Expires:  time.Unix(0, 0),
		MaxAge:   -1,
	})
}

// isRequestSecure detects whether the original client request used HTTPS.
// It checks TLS state directly first; failing that, it trusts the standard
// X-Forwarded-Proto header which Traefik / NGINX set for upstreams.
func isRequestSecure(r *http.Request) bool {
	if r.TLS != nil {
		return true
	}
	return strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https")
}

// decodeJSONBody decodes a JSON body, writing a 400 response on failure.
// Returns true on success.
func decodeJSONBody(w http.ResponseWriter, r *http.Request, into any) bool {
	if r.Body == nil {
		writeError(w, http.StatusBadRequest, "missing JSON body")
		return false
	}
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(into); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return false
	}
	return true
}

// validUsername enforces a tight charset: 3..32 chars, alphanumerics plus
// "._-". No spaces (avoids login UX confusion).
func validUsername(s string) bool {
	if n := utf8.RuneCountInString(s); n < 3 || n > 32 {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '.' || r == '_' || r == '-':
		default:
			return false
		}
	}
	return true
}

func validPassword(s string) bool {
	return utf8.RuneCountInString(s) >= minPasswordRunes
}

// generateOpaqueToken returns a URL-safe random token of the given byte length.
func generateOpaqueToken(nBytes int) (string, error) {
	buf := make([]byte, nBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// generatePassword returns a base64url-encoded random password of approx
// `nChars` characters (will round up to the nearest 4 from the byte count).
func generatePassword(nChars int) (string, error) {
	// 3 bytes → 4 chars of base64url
	nBytes := (nChars*3 + 3) / 4
	buf := make([]byte, nBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	s := base64.RawURLEncoding.EncodeToString(buf)
	if utf8.RuneCountInString(s) > nChars {
		s = s[:nChars]
	}
	return s, nil
}
