package server

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"
	"unicode/utf8"

	"golang.org/x/crypto/bcrypt"
)

// dummyHash is a real bcrypt hash precomputed at init so the unknown-user
// branch of login can run CompareHashAndPassword and exhibit the same wall-
// clock cost as a real comparison — defeating timing-based username probing.
// The plaintext is unrelated to any real password.
var dummyHash []byte

func init() {
	h, err := bcrypt.GenerateFromPassword([]byte("triagearr-timing-equalizer"), bcrypt.DefaultCost)
	if err != nil {
		panic("init dummy bcrypt hash: " + err.Error())
	}
	dummyHash = h
}

// sessionCookieName is the cookie carrying the opaque session token.
const sessionCookieName = "triagearr_session"

// generatedPasswordLength is the number of base64url chars the server hands
// back to the operator when they ask for an auto-generated password.
const generatedPasswordLength = 32

// minPasswordRunes is the minimum length for an operator-chosen password.
// Short by browser-form standards on purpose: the dashboard is single-user
// and the cookie/X-API-Key flow is rate-limited.
const minPasswordRunes = 12

type sessionStatusResponse struct {
	AuthEnabled   bool   `json:"auth_enabled"`
	Authenticated bool   `json:"authenticated"`
	Username      string `json:"username,omitempty"`
}

func (s *Server) handleSessionStatus(w http.ResponseWriter, r *http.Request) {
	resp := sessionStatusResponse{}
	enabled, err := s.authEnabled(r.Context())
	if err != nil {
		writeInternal(w, err)
		return
	}
	resp.AuthEnabled = enabled
	if enabled {
		if uid, ok := s.resolveSession(r); ok {
			if u, err := s.opts.Store.GetAuthUserByID(r.Context(), uid); err == nil {
				resp.Authenticated = true
				resp.Username = u.Username
			}
		}
	}
	writeJSON(w, http.StatusOK, resp)
}

type sessionLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (s *Server) handleSessionLogin(w http.ResponseWriter, r *http.Request) {
	var req sessionLoginRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	enabled, err := s.authEnabled(r.Context())
	if err != nil {
		writeInternal(w, err)
		return
	}
	if !enabled {
		writeError(w, http.StatusBadRequest, "authentication is not enabled")
		return
	}
	user, err := s.opts.Store.GetAuthUserByName(r.Context(), strings.TrimSpace(req.Username))
	if err != nil {
		// Burn the bcrypt cost against a real hash so unknown-user latency
		// matches wrong-password latency.
		_ = bcrypt.CompareHashAndPassword(dummyHash, []byte(req.Password))
		writeError(w, http.StatusUnauthorized, "invalid credentials")
		return
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Password)); err != nil {
		writeError(w, http.StatusUnauthorized, "invalid credentials")
		return
	}
	if err := s.issueSession(w, r, user.ID); err != nil {
		writeInternal(w, err)
		return
	}
	writeJSON(w, http.StatusOK, sessionStatusResponse{
		AuthEnabled: true, Authenticated: true, Username: user.Username,
	})
}

func (s *Server) handleSessionLogout(w http.ResponseWriter, r *http.Request) {
	if c, err := r.Cookie(sessionCookieName); err == nil && c.Value != "" {
		_ = s.opts.Store.DeleteAuthSession(r.Context(), hashToken(c.Value))
	}
	clearSessionCookie(w, r)
	writeJSON(w, http.StatusOK, map[string]string{"status": "logged_out"})
}

type authEnableRequest struct {
	Username string `json:"username"`
	Password string `json:"password,omitempty"` // optional; auto-generated when empty
}

type authEnableResponse struct {
	Username string `json:"username"`
	Password string `json:"password,omitempty"` // present only when auto-generated
}

func (s *Server) handleAuthEnable(w http.ResponseWriter, r *http.Request) {
	enabled, err := s.authEnabled(r.Context())
	if err != nil {
		writeInternal(w, err)
		return
	}
	if enabled {
		writeError(w, http.StatusConflict, "authentication is already enabled — use POST /api/v1/auth/password to rotate the password")
		return
	}
	var req authEnableRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	username := strings.TrimSpace(req.Username)
	if !validUsername(username) {
		writeError(w, http.StatusBadRequest, "username must be 3..32 chars, letters/digits/._-")
		return
	}
	password, hash, autoGenerated, err := resolveNewPassword(req.Password)
	if err != nil {
		if errors.Is(err, errBadPassword) {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		writeInternal(w, err)
		return
	}
	uid, err := s.opts.Store.InsertAuthUser(r.Context(), username, hash)
	if err != nil {
		writeInternal(w, fmt.Errorf("creating user: %w", err))
		return
	}
	s.invalidateAuthState()
	if err := s.issueSession(w, r, uid); err != nil {
		writeInternal(w, err)
		return
	}
	resp := authEnableResponse{Username: username}
	if autoGenerated {
		resp.Password = password // shown to the operator exactly once
	}
	writeJSON(w, http.StatusOK, resp)
}

type authDisableRequest struct {
	Password string `json:"password"`
}

func (s *Server) handleAuthDisable(w http.ResponseWriter, r *http.Request) {
	var req authDisableRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	uid, ok := userIDFromContext(r.Context())
	if !ok {
		// X-API-Key path: still require the current password to confirm.
		writeError(w, http.StatusForbidden, "disable must be performed from an authenticated UI session")
		return
	}
	user, err := s.opts.Store.GetAuthUserByID(r.Context(), uid)
	if err != nil {
		writeInternal(w, err)
		return
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Password)); err != nil {
		writeError(w, http.StatusUnauthorized, "invalid password")
		return
	}
	if err := s.opts.Store.DeleteAuthUser(r.Context(), uid); err != nil {
		writeInternal(w, err)
		return
	}
	s.invalidateAuthState()
	clearSessionCookie(w, r)
	writeJSON(w, http.StatusOK, map[string]string{"status": "disabled"})
}

type authChangePasswordRequest struct {
	Current string `json:"current"`
	New     string `json:"new,omitempty"`
}

type authChangePasswordResponse struct {
	Password string `json:"password,omitempty"` // present only when auto-generated
}

func (s *Server) handleAuthChangePassword(w http.ResponseWriter, r *http.Request) {
	var req authChangePasswordRequest
	if !decodeJSONBody(w, r, &req) {
		return
	}
	uid, ok := userIDFromContext(r.Context())
	if !ok {
		writeError(w, http.StatusForbidden, "password change must be performed from an authenticated UI session")
		return
	}
	user, err := s.opts.Store.GetAuthUserByID(r.Context(), uid)
	if err != nil {
		writeInternal(w, err)
		return
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(req.Current)); err != nil {
		writeError(w, http.StatusUnauthorized, "invalid current password")
		return
	}
	newPwd, hash, autoGenerated, err := resolveNewPassword(req.New)
	if err != nil {
		if errors.Is(err, errBadPassword) {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		writeInternal(w, err)
		return
	}
	if subtle.ConstantTimeCompare([]byte(req.Current), []byte(newPwd)) == 1 {
		writeError(w, http.StatusBadRequest, "new password must differ from the current one")
		return
	}
	if err := s.opts.Store.UpdateAuthPassword(r.Context(), uid, hash); err != nil {
		writeInternal(w, err)
		return
	}
	resp := authChangePasswordResponse{}
	if autoGenerated {
		resp.Password = newPwd
	}
	writeJSON(w, http.StatusOK, resp)
}

// resolveNewPassword returns the plaintext password to use (auto-generating
// one when supplied is empty), its bcrypt hash, and whether it was generated.
func resolveNewPassword(supplied string) (plain, hash string, autoGenerated bool, err error) {
	plain = supplied
	if plain == "" {
		plain, err = generatePassword(generatedPasswordLength)
		if err != nil {
			return "", "", false, fmt.Errorf("generating password: %w", err)
		}
		autoGenerated = true
	}
	if !validPassword(plain) {
		return "", "", false, errBadPassword
	}
	h, err := bcrypt.GenerateFromPassword([]byte(plain), bcrypt.DefaultCost)
	if err != nil {
		return "", "", false, fmt.Errorf("hashing password: %w", err)
	}
	return plain, string(h), autoGenerated, nil
}

// errBadPassword is returned by resolveNewPassword to signal a client-facing
// 400 (password too short). The handler distinguishes it from internal errors.
var errBadPassword = fmt.Errorf("password must be at least %d characters", minPasswordRunes)

// issueSession mints a fresh opaque token, persists its hash, and sets the
// session cookie on the response.
func (s *Server) issueSession(w http.ResponseWriter, r *http.Request, userID int64) error {
	token, err := generateOpaqueToken(32)
	if err != nil {
		return fmt.Errorf("generating session token: %w", err)
	}
	expires := time.Now().UTC().Add(sessionTTL)
	if err := s.opts.Store.InsertAuthSession(r.Context(), hashToken(token), userID, expires); err != nil {
		return err
	}
	http.SetCookie(w, &http.Cookie{ //nolint:gosec // HttpOnly/SameSite set below; Secure tracks request scheme.
		Name:     sessionCookieName,
		Value:    token,
		Path:     "/",
		HttpOnly: true,
		Secure:   isRequestSecure(r),
		SameSite: http.SameSiteLaxMode,
		Expires:  expires,
	})
	return nil
}

func clearSessionCookie(w http.ResponseWriter, r *http.Request) {
	http.SetCookie(w, &http.Cookie{ //nolint:gosec // HttpOnly/SameSite set below; Secure tracks request scheme.
		Name:     sessionCookieName,
		Value:    "",
		Path:     "/",
		HttpOnly: true,
		Secure:   isRequestSecure(r),
		SameSite: http.SameSiteLaxMode,
		Expires:  time.Unix(0, 0),
		MaxAge:   -1,
	})
}

// isRequestSecure detects whether the original client request used HTTPS.
// It checks TLS state directly first; failing that, it trusts the standard
// X-Forwarded-Proto header which Traefik / NGINX set for upstreams.
func isRequestSecure(r *http.Request) bool {
	if r.TLS != nil {
		return true
	}
	return strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https")
}

// decodeJSONBody decodes a JSON body, writing a 400 response on failure.
// Returns true on success.
func decodeJSONBody(w http.ResponseWriter, r *http.Request, into any) bool {
	if r.Body == nil {
		writeError(w, http.StatusBadRequest, "missing JSON body")
		return false
	}
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(into); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return false
	}
	return true
}

// validUsername enforces a tight charset: 3..32 chars, alphanumerics plus
// "._-". No spaces (avoids login UX confusion).
func validUsername(s string) bool {
	if n := utf8.RuneCountInString(s); n < 3 || n > 32 {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '.' || r == '_' || r == '-':
		default:
			return false
		}
	}
	return true
}

func validPassword(s string) bool {
	return utf8.RuneCountInString(s) >= minPasswordRunes
}

// generateOpaqueToken returns a URL-safe random token of the given byte length.
func generateOpaqueToken(nBytes int) (string, error) {
	buf := make([]byte, nBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// generatePassword returns a base64url-encoded random password of approx
// `nChars` characters (will round up to the nearest 4 from the byte count).
func generatePassword(nChars int) (string, error) {
	// 3 bytes → 4 chars of base64url
	nBytes := (nChars*3 + 3) / 4
	buf := make([]byte, nBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	s := base64.RawURLEncoding.EncodeToString(buf)
	if utf8.RuneCountInString(s) > nChars {
		s = s[:nChars]
	}
	return s, nil
}
