/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorrentsRouteImport } from './routes/torrents'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorrentsHashRouteImport } from './routes/torrents.$hash'

const TorrentsRoute = TorrentsRouteImport.update({
  id: '/torrents',
  path: '/torrents',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorrentsHashRoute = TorrentsHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => TorrentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/torrents': typeof TorrentsRouteWithChildren
  '/torrents/$hash': typeof TorrentsHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/torrents': typeof TorrentsRouteWithChildren
  '/torrents/$hash': typeof TorrentsHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/torrents': typeof TorrentsRouteWithChildren
  '/torrents/$hash': typeof TorrentsHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/actions' | '/settings' | '/torrents' | '/torrents/$hash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actions' | '/settings' | '/torrents' | '/torrents/$hash'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/settings'
    | '/torrents'
    | '/torrents/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  SettingsRoute: typeof SettingsRoute
  TorrentsRoute: typeof TorrentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torrents': {
      id: '/torrents'
      path: '/torrents'
      fullPath: '/torrents'
      preLoaderRoute: typeof TorrentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torrents/$hash': {
      id: '/torrents/$hash'
      path: '/$hash'
      fullPath: '/torrents/$hash'
      preLoaderRoute: typeof TorrentsHashRouteImport
      parentRoute: typeof TorrentsRoute
    }
  }
}

interface TorrentsRouteChildren {
  TorrentsHashRoute: typeof TorrentsHashRoute
}

const TorrentsRouteChildren: TorrentsRouteChildren = {
  TorrentsHashRoute: TorrentsHashRoute,
}

const TorrentsRouteWithChildren = TorrentsRoute._addFileChildren(
  TorrentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  SettingsRoute: SettingsRoute,
  TorrentsRoute: TorrentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
